<?php
// =============================================================================
// LAMP Stack — Default Landing Page + Site Manager
// Place at: /mnt/user/VM/Dockers/LampStack/websites/default/index.php
// Requires: /mnt/user/VM/Dockers/LampStack/websites/.env (one level up)
// Remove the existing index.html after deploying this file.
// =============================================================================

// --- Load environment config -------------------------------------------------
$envPath = '/var/www/config/env/.env';
if (!file_exists($envPath)) {
    die('Configuration error: .env file not found at ' . $envPath . '<br>Expected at /mnt/user/VM/Dockers/LampStack/config/env/.env on UnRAID host.');
}
$env = parse_ini_file($envPath);

define('WEBSITES_DIR',   '/var/www/html');
define('VHOSTS_DIR',     '/etc/apache2/sites-available/vhosts');
define('DEFAULT_SITE',   'default');
define('SERVER_IP',      $env['SERVER_IP']);
define('PIHOLE_HOST',    $env['PIHOLE_HOST']);
define('PIHOLE_API_KEY', $env['PIHOLE_API_KEY']);

// --- AJAX Action Handler -----------------------------------------------------
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'])) {
    header('Content-Type: application/json');

    $action = trim($_POST['action'] ?? '');
    $site   = trim($_POST['site']   ?? '');

    if (!preg_match('/^[a-zA-Z0-9_\-]+$/', $site) || strpos($site, '000') === 0) {
        echo json_encode(['success' => false, 'message' => 'Invalid site name. Use letters, numbers, hyphens and underscores only. Names cannot start with "000".']);
        exit;
    }
    if ($site === DEFAULT_SITE) {
        echo json_encode(['success' => false, 'message' => 'Cannot modify the default site.']);
        exit;
    }

    $sitePath  = WEBSITES_DIR . '/' . $site;
    $vhostFile = VHOSTS_DIR   . '/' . $site . '.conf';
    $domain    = $site . '.local';
    $messages  = [];

    // ── Create ────────────────────────────────────────────────────────────────
    if ($action === 'create') {
        if (is_dir($sitePath)) {
            echo json_encode(['success' => false, 'message' => "Site '{$site}' already exists."]);
            exit;
        }
        if (!mkdir($sitePath, 0777, true)) {
            echo json_encode(['success' => false, 'message' => "Failed to create site folder at {$sitePath}."]);
            exit;
        }
        chmod($sitePath, 0777);

        $indexHtml = <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{$domain}</title>
    <style>
        body { font-family: monospace; background: #0e1117; color: #f4a137;
               display: flex; align-items: center; justify-content: center;
               height: 100vh; margin: 0; }
        p { color: #7a8499; }
    </style>
</head>
<body>
    <div style="text-align:center">
        <h1>&#9679; {$domain}</h1>
        <p>Site created. Replace this file with your content.</p>
    </div>
</body>
</html>
HTML;
        file_put_contents($sitePath . '/index.html', $indexHtml);
        $messages[] = "Created site folder and placeholder index.html.";

        $vhostContent = <<<CONF
# Generated by LAMP Site Manager
<VirtualHost *:80>
    ServerName {$domain}
    DocumentRoot /var/www/html/{$site}

    <Directory /var/www/html/{$site}>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog  \${APACHE_LOG_DIR}/{$site}-error.log
    CustomLog \${APACHE_LOG_DIR}/{$site}-access.log combined
</VirtualHost>
CONF;
        if (file_put_contents($vhostFile, $vhostContent) === false) {
            $messages[] = "WARNING: Could not write vhost config. Check permissions on " . VHOSTS_DIR;
        } else {
            $messages[] = "Created vhost config.";
        }

        $messages[] = pihole_dns($domain, SERVER_IP, 'add');
        $messages[] = apache_graceful();

        echo json_encode(['success' => true, 'message' => implode("\n", $messages)]);
        exit;
    }

    // ── Delete ────────────────────────────────────────────────────────────────
    if ($action === 'delete') {
        if (!is_dir($sitePath)) {
            echo json_encode(['success' => false, 'message' => "Site folder '{$site}' not found."]);
            exit;
        }

        $errors = [];

        if (!rrmdir($sitePath)) {
            $errors[] = "Failed to fully remove site folder.";
        } else {
            $messages[] = "Deleted site folder.";
        }

        if (file_exists($vhostFile)) {
            if (!unlink($vhostFile)) {
                $errors[] = "Failed to remove vhost config.";
            } else {
                $messages[] = "Deleted vhost config.";
            }
        } else {
            $messages[] = "No vhost config found (already removed).";
        }

        $messages[] = pihole_dns($domain, SERVER_IP, 'delete');
        $messages[] = apache_graceful();

        if (!empty($errors)) {
            echo json_encode(['success' => false, 'message' => implode("\n", array_merge($messages, $errors))]);
        } else {
            echo json_encode(['success' => true, 'message' => implode("\n", $messages)]);
        }
        exit;
    }

    echo json_encode(['success' => false, 'message' => 'Unknown action.']);
    exit;
}

// --- Helpers -----------------------------------------------------------------

// Pi-hole v6 REST API: authenticate then PUT/DELETE the DNS host record.
function pihole_dns(string $domain, string $ip, string $action): string {
    // Step 1: authenticate and get session SID + CSRF token
    $authUrl  = PIHOLE_HOST . '/api/auth';
    $authBody = json_encode(['password' => PIHOLE_API_KEY]);
    $authCtx  = stream_context_create(['http' => [
        'method'  => 'POST',
        'header'  => "Content-Type: application/json\r\nContent-Length: " . strlen($authBody) . "\r\n",
        'content' => $authBody,
        'timeout' => 5,
        'ignore_errors' => true,
    ]]);
    $authRes = @file_get_contents($authUrl, false, $authCtx);
    if ($authRes === false) {
        return "WARNING: Could not reach Pi-hole at " . PIHOLE_HOST . ". DNS record not updated.";
    }
    $authJson = json_decode($authRes, true);
    $sid  = $authJson['session']['sid']  ?? null;
    $csrf = $authJson['session']['csrf'] ?? null;
    if (!$sid) {
        return "WARNING: Pi-hole auth failed (check app password). Response: " . htmlspecialchars($authRes);
    }

    // Step 2: PUT or DELETE /api/config/dns/hosts/{ip}%20{domain}
    $entry  = urlencode($ip . ' ' . $domain);
    $dnsUrl = PIHOLE_HOST . '/api/config/dns/hosts/' . $entry;
    $method = ($action === 'add') ? 'PUT' : 'DELETE';
    $dnsCtx = stream_context_create(['http' => [
        'method'  => $method,
        'header'  => "Content-Type: application/json\r\nX-CSRF-Token: {$csrf}\r\nCookie: SID={$sid}\r\n",
        'timeout' => 5,
        'ignore_errors' => true,
    ]]);
    @file_get_contents($dnsUrl, false, $dnsCtx);

    // v6 returns 201 on add, 204 on delete
    $httpCode = 0;
    foreach ($http_response_header ?? [] as $h) {
        if (preg_match('#^HTTP/\S+\s+(\d+)#', $h, $m)) $httpCode = (int)$m[1];
    }
    if (in_array($httpCode, [200, 201, 204])) {
        $verb = ($action === 'add') ? 'added' : 'deleted';
        return "Pi-hole DNS record {$verb}: {$domain} → {$ip}";
    }
    return "Pi-hole DNS warning (HTTP {$httpCode})";
}

// Apache graceful reload — sends USR1 to PID 1 (Apache master process).
// Equivalent to apachectl graceful; no sudo required inside the container.
function apache_graceful(): string {
    $output = shell_exec('kill -USR1 1 2>&1');
    if ($output === null || trim($output) === '') {
        return "Apache reloaded automatically.";
    }
    return "Apache reload warning: " . htmlspecialchars(trim($output));
}

// Recursively delete a directory and all its contents.
function rrmdir(string $path): bool {
    if (!is_dir($path)) return false;
    $items = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($path, RecursiveDirectoryIterator::SKIP_DOTS),
        RecursiveIteratorIterator::CHILD_FIRST
    );
    foreach ($items as $item) {
        $item->isDir() ? rmdir($item->getRealPath()) : unlink($item->getRealPath());
    }
    return rmdir($path);
}

// Return sorted list of site folders, excluding hidden/system entries.
function get_sites(): array {
    $sites = [];
    if (!is_dir(WEBSITES_DIR)) return $sites;
    foreach (scandir(WEBSITES_DIR) as $entry) {
        if ($entry === '.' || $entry === '..') continue;
        if (is_dir(WEBSITES_DIR . '/' . $entry)) $sites[] = $entry;
    }
    sort($sites);
    return $sites;
}

$sites     = get_sites();
$siteCount = count($sites);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LAMP Stack — Local Development Server</title>
    <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600&family=Syne:wght@400;600;700;800&display=swap" rel="stylesheet">
    <style>
        /* =====================================================================
           LAMP Stack - Default Landing Page + Site Manager
           ===================================================================== */

        :root {
            --bg:           #0e1117;
            --bg-card:      #161b25;
            --bg-card-alt:  #1c2333;
            --border:       rgba(255,255,255,0.08);
            --border-hover: rgba(255,255,255,0.16);
            --text:         #e8eaf0;
            --text-muted:   #7a8499;
            --text-dim:     #4a5268;
            --accent:       #f4a137;
            --accent-dim:   rgba(244,161,55,0.12);
            --accent-glow:  rgba(244,161,55,0.25);
            --green:        #3dd68c;
            --green-dim:    rgba(61,214,140,0.12);
            --blue:         #60a5fa;
            --blue-dim:     rgba(96,165,250,0.12);
            --red:          #ff4757;
            --red-dim:      rgba(255,71,87,0.12);
            --warn:         #ffa502;
        }

        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
            background: var(--bg);
            color: var(--text);
            font-family: 'Syne', sans-serif;
            min-height: 100vh;
            padding: 2rem;
        }

        body::before {
            content: '';
            position: fixed; inset: 0; z-index: 0; pointer-events: none;
            background: repeating-linear-gradient(
                0deg, transparent, transparent 2px,
                rgba(0,0,0,0.06) 2px, rgba(0,0,0,0.06) 4px
            );
        }

        header, main, footer { position: relative; z-index: 1; }

        header {
            max-width: 960px; margin: 0 auto 3rem;
            display: flex; align-items: center; justify-content: space-between;
            padding-bottom: 1.5rem; border-bottom: 1px solid var(--border);
        }

        .logo { display: flex; align-items: center; gap: 1rem; }

        .logo-icon {
            width: 42px; height: 42px; background: var(--accent-dim);
            border: 1px solid var(--accent-glow); border-radius: 10px;
            display: flex; align-items: center; justify-content: center;
        }

        .logo-text h1 { font-size: 1.1rem; font-weight: 600; color: var(--text); letter-spacing: 0.02em; }
        .logo-text p  { font-size: 0.75rem; color: var(--text-muted); font-family: 'JetBrains Mono', monospace; margin-top: 2px; }

        .status-pill {
            display: flex; align-items: center; gap: 8px;
            background: var(--green-dim); border: 1px solid rgba(61,214,140,0.2);
            border-radius: 999px; padding: 6px 14px;
            font-size: 0.75rem; color: var(--green); font-family: 'JetBrains Mono', monospace;
        }

        .status-dot {
            width: 7px; height: 7px; background: var(--green); border-radius: 50%;
            animation: pulse 2s ease-in-out infinite;
        }

        @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }

        main { max-width: 960px; margin: 0 auto; }

        .stack-grid {
            display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem; margin-bottom: 2rem;
        }

        .stack-card {
            background: var(--bg-card); border: 1px solid var(--border);
            border-radius: 12px; padding: 1.25rem; transition: border-color 0.2s;
        }
        .stack-card:hover { border-color: var(--border-hover); }

        .stack-card-label {
            font-size: 0.7rem; font-family: 'JetBrains Mono', monospace;
            color: var(--text-dim); text-transform: uppercase;
            letter-spacing: 0.08em; margin-bottom: 0.6rem;
        }

        .stack-card-value { font-size: 1rem; font-weight: 600; color: var(--text); margin-bottom: 0.3rem; }

        .tag {
            display: inline-block; padding: 2px 8px; border-radius: 4px;
            font-size: 0.7rem; font-family: 'JetBrains Mono', monospace; font-weight: 500;
        }
        .tag-green { background: var(--green-dim); color: var(--green); }
        .tag-blue  { background: var(--blue-dim);  color: var(--blue);  }

        .section-header {
            display: flex; align-items: center; justify-content: space-between; margin-bottom: 1rem;
        }

        .section-title {
            font-size: 0.8rem; font-family: 'JetBrains Mono', monospace;
            color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.08em;
        }

        .section-badge {
            font-size: 0.72rem; font-family: 'JetBrains Mono', monospace;
            color: var(--text-dim); background: var(--bg-card);
            border: 1px solid var(--border); padding: 2px 10px; border-radius: 20px;
        }

        .create-bar {
            background: var(--bg-card); border: 1px solid var(--border);
            border-radius: 12px; padding: 1.1rem 1.25rem;
            display: flex; gap: 0.75rem; align-items: flex-end;
            flex-wrap: wrap; margin-bottom: 1rem;
        }

        .create-bar-field { display: flex; flex-direction: column; gap: 0.3rem; flex: 1; min-width: 180px; }

        .create-bar-field label {
            font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.1em;
            color: var(--text-dim); font-family: 'JetBrains Mono', monospace;
        }

        .create-bar-field input {
            background: var(--bg); border: 1px solid var(--border); color: var(--text);
            font-family: 'JetBrains Mono', monospace; font-size: 0.88rem;
            padding: 0.45rem 0.75rem; border-radius: 8px; outline: none;
            transition: border-color 0.15s; width: 100%;
        }
        .create-bar-field input:focus { border-color: var(--accent); }
        .create-bar-field input::placeholder { color: var(--text-dim); }

        .create-hint { font-size: 0.68rem; color: var(--text-dim); font-family: 'JetBrains Mono', monospace; margin-top: 0.2rem; }

        .btn {
            font-family: 'JetBrains Mono', monospace; font-size: 0.8rem; font-weight: 600;
            border: none; border-radius: 8px; padding: 0.48rem 1rem; cursor: pointer;
            transition: opacity 0.15s, transform 0.1s; white-space: nowrap; flex-shrink: 0;
        }
        .btn:active { transform: scale(0.97); }
        .btn:disabled { opacity: 0.4; cursor: not-allowed; }

        .btn-accent { background: var(--accent); color: #000; border: 1px solid var(--accent); }
        .btn-accent:hover:not(:disabled) { opacity: 0.85; }

        .btn-danger {
            background: var(--red-dim); color: var(--red);
            border: 1px solid rgba(255,71,87,0.25); font-size: 0.75rem; padding: 0.35rem 0.75rem;
        }
        .btn-danger:hover:not(:disabled) { background: rgba(255,71,87,0.22); }

        .btn-ghost {
            background: transparent; color: var(--text-muted); border: 1px solid var(--border);
            font-family: 'JetBrains Mono', monospace; font-size: 0.8rem; padding: 0.48rem 1rem;
            border-radius: 8px; cursor: pointer;
        }
        .btn-ghost:hover { border-color: var(--border-hover); color: var(--text); }

        .sites-grid {
            display: grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
            gap: 0.75rem; margin-bottom: 2rem;
        }

        .site-card {
            background: var(--bg-card); border: 1px solid var(--border); border-radius: 12px;
            padding: 1.1rem 1.25rem; display: flex; align-items: center;
            justify-content: space-between; gap: 0.75rem;
            transition: border-color 0.2s, background 0.2s;
        }
        .site-card:hover { border-color: var(--border-hover); background: var(--bg-card-alt); }
        .site-card.is-default { opacity: 0.6; cursor: default; }
        .site-card.is-default:hover { border-color: var(--border); background: var(--bg-card); }

        .site-info { display: flex; align-items: center; gap: 0.75rem; min-width: 0; }

        .site-icon {
            width: 34px; height: 34px; border-radius: 8px;
            display: flex; align-items: center; justify-content: center;
            font-size: 16px; flex-shrink: 0; background: var(--accent-dim);
        }
        .site-icon.default-icon { background: var(--bg-card-alt); }

        .site-label { font-size: 0.88rem; font-weight: 600; color: var(--text); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
        .site-domain { font-size: 0.72rem; color: var(--text-muted); font-family: 'JetBrains Mono', monospace; }
        .site-link { text-decoration: none; color: var(--text); transition: color 0.15s; }
        .site-link:hover { color: var(--accent); }

        .tag-default {
            font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.08em;
            color: var(--accent); background: var(--accent-dim); padding: 2px 8px;
            border-radius: 4px; flex-shrink: 0; font-family: 'JetBrains Mono', monospace;
        }

        .links-grid {
            display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem; margin-bottom: 2rem;
        }

        .link-card {
            background: var(--bg-card); border: 1px solid var(--border); border-radius: 12px;
            padding: 1.25rem; text-decoration: none; color: inherit;
            display: flex; align-items: center; gap: 1rem;
            transition: border-color 0.2s, background 0.2s;
        }
        .link-card:hover { border-color: var(--border-hover); background: var(--bg-card-alt); }

        .link-icon {
            width: 38px; height: 38px; border-radius: 9px;
            display: flex; align-items: center; justify-content: center;
            font-size: 18px; flex-shrink: 0;
        }
        .link-icon-amber { background: var(--accent-dim); }
        .link-icon-green { background: var(--green-dim); }

        .link-title { font-size: 0.85rem; font-weight: 600; color: var(--text); }
        .link-desc  { font-size: 0.72rem; color: var(--text-muted); margin-top: 2px; }

        footer {
            max-width: 960px; margin: 2rem auto 0; padding-top: 1.5rem;
            border-top: 1px solid var(--border);
            display: flex; align-items: center; justify-content: space-between;
        }
        footer p { font-size: 0.72rem; color: var(--text-dim); font-family: 'JetBrains Mono', monospace; }
        footer a { color: var(--text-dim); text-decoration: none; transition: color 0.2s; }
        footer a:hover { color: var(--accent); }

        .fade-in { opacity: 0; transform: translateY(12px); animation: fadeIn 0.5s ease forwards; }
        .fade-in:nth-child(1) { animation-delay: 0.05s; }
        .fade-in:nth-child(2) { animation-delay: 0.10s; }
        .fade-in:nth-child(3) { animation-delay: 0.15s; }
        .fade-in:nth-child(4) { animation-delay: 0.20s; }
        .fade-in:nth-child(5) { animation-delay: 0.25s; }
        .fade-in:nth-child(6) { animation-delay: 0.30s; }
        @keyframes fadeIn { to { opacity: 1; transform: translateY(0); } }

        .spinner {
            display: inline-block; width: 11px; height: 11px;
            border: 2px solid rgba(0,0,0,0.2); border-top-color: #000;
            border-radius: 50%; animation: spin 0.6s linear infinite;
            vertical-align: middle; margin-right: 0.3rem;
        }
        @keyframes spin { to { transform: rotate(360deg); } }

        #modal-overlay {
            display: none; position: fixed; inset: 0; z-index: 50;
            background: rgba(0,0,0,0.7); backdrop-filter: blur(3px);
            align-items: center; justify-content: center;
        }
        #modal-overlay.open { display: flex; }

        #modal-box {
            background: var(--bg-card); border: 1px solid rgba(255,71,87,0.3);
            border-radius: 12px; padding: 1.75rem 2rem; max-width: 420px; width: 90%;
            box-shadow: 0 20px 60px rgba(0,0,0,0.6);
        }
        #modal-box h3 { font-family: 'Syne', sans-serif; font-size: 1.05rem; color: var(--red); margin-bottom: 0.75rem; }
        #modal-box p  { font-size: 0.84rem; color: var(--text-muted); line-height: 1.7; margin-bottom: 1.5rem; }
        #modal-box p strong { color: var(--text); }
        .modal-actions { display: flex; gap: 0.75rem; justify-content: flex-end; }

        #toast {
            position: fixed; bottom: 1.5rem; right: 1.5rem; z-index: 100;
            max-width: 420px; background: var(--bg-card); border: 1px solid var(--border);
            border-radius: 12px; padding: 1rem 1.25rem; font-size: 0.82rem; line-height: 1.6;
            box-shadow: 0 8px 32px rgba(0,0,0,0.5); display: none;
            animation: slideIn 0.2s ease; font-family: 'JetBrains Mono', monospace;
        }
        @keyframes slideIn { from { transform: translateY(10px); opacity: 0; } to { transform: translateY(0); opacity: 1; } }
        #toast.success { border-color: rgba(61,214,140,0.4); }
        #toast.error   { border-color: rgba(255,71,87,0.4); }
        .toast-title { font-family: 'Syne', sans-serif; font-weight: 700; font-size: 0.88rem; margin-bottom: 0.4rem; }
        #toast.success .toast-title { color: var(--green); }
        #toast.error   .toast-title { color: var(--red); }
        #toast code { background: var(--bg); padding: 0.1rem 0.35rem; border-radius: 3px; font-size: 0.78rem; }
        .toast-close { float: right; background: none; border: none; color: var(--text-dim); cursor: pointer; font-size: 1rem; line-height: 1; margin-left: 0.75rem; }
        .toast-close:hover { color: var(--text); }
    </style>
</head>
<body>

<header>
    <div class="logo">
        <div class="logo-icon">
            <img src="lamp-icon.png" alt="LAMP Stack" style="width:28px;height:28px;object-fit:contain;">
        </div>
        <div class="logo-text">
            <h1>LAMP Stack</h1>
            <p>local development server</p>
        </div>
    </div>
    <div class="status-pill">
        <div class="status-dot"></div>
        stack running
    </div>
</header>

<main>

    <div class="section-header fade-in">
        <span class="section-title">Stack Components</span>
    </div>

    <div class="stack-grid fade-in">
        <div class="stack-card">
            <div class="stack-card-label">Web Server</div>
            <div class="stack-card-value">Apache 2.4</div>
            <span class="tag tag-green">running</span>
        </div>
        <div class="stack-card">
            <div class="stack-card-label">PHP Version</div>
            <div class="stack-card-value">PHP 8.3</div>
            <span class="tag tag-green">with composer</span>
        </div>
        <div class="stack-card">
            <div class="stack-card-label">Database</div>
            <div class="stack-card-value">MariaDB 11</div>
            <span class="tag tag-green">running</span>
        </div>
        <div class="stack-card">
            <div class="stack-card-label">DB Management</div>
            <div class="stack-card-value">phpMyAdmin</div>
            <span class="tag tag-blue">port 8080</span>
        </div>
    </div>

    <div class="section-header fade-in">
        <span class="section-title">Active Sites</span>
        <span class="section-badge" id="site-count-badge"><?= $siteCount ?> total</span>
    </div>

    <div class="create-bar fade-in">
        <div class="create-bar-field">
            <label for="new-site-name">New Site Name</label>
            <input type="text" id="new-site-name" placeholder="mysite" autocomplete="off"
                   spellcheck="false" pattern="[a-zA-Z0-9_\-]+">
            <div class="create-hint">→ creates mysite.local pointing to <?= SERVER_IP ?></div>
        </div>
        <button class="btn btn-accent" id="btn-create" onclick="createSite()">+ Create Site</button>
    </div>

    <div class="sites-grid fade-in" id="sites-grid">
        <?php foreach ($sites as $site):
            $isDefault = ($site === DEFAULT_SITE);
        ?>
        <div class="site-card <?= $isDefault ? 'is-default' : '' ?>" id="card-<?= htmlspecialchars($site) ?>">
            <div class="site-info">
                <div class="site-icon <?= $isDefault ? 'default-icon' : '' ?>">
                    <?= $isDefault ? '🔒' : '🌐' ?>
                </div>
                <div>
                    <?php if ($isDefault): ?>
                        <div class="site-label"><?= htmlspecialchars($site) ?></div>
                    <?php else: ?>
                        <a class="site-label site-link"
                           href="http://<?= htmlspecialchars($site) ?>.local"
                           target="_blank"><?= htmlspecialchars($site) ?></a>
                    <?php endif; ?>
                    <div class="site-domain"><?= htmlspecialchars($site) ?>.local</div>
                </div>
            </div>
            <?php if ($isDefault): ?>
                <span class="tag-default">default</span>
            <?php else: ?>
                <button class="btn btn-danger"
                        onclick="confirmDelete('<?= addslashes(htmlspecialchars($site)) ?>')">
                    Delete
                </button>
            <?php endif; ?>
        </div>
        <?php endforeach; ?>
    </div>

    <div class="section-header fade-in">
        <span class="section-title">Quick Links</span>
    </div>

    <div class="links-grid fade-in">
        <a class="link-card" href="http://192.168.0.2:8080" target="_blank">
            <div class="link-icon link-icon-amber">🗄</div>
            <div>
                <div class="link-title">phpMyAdmin</div>
                <div class="link-desc">Database management UI</div>
            </div>
        </a>
        <a class="link-card" href="https://github.com/EddCase/unraid-lamp-stack" target="_blank">
            <div class="link-icon link-icon-green">📦</div>
            <div>
                <div class="link-title">GitHub Repo</div>
                <div class="link-desc">Source code &amp; documentation</div>
            </div>
        </a>
    </div>

</main>

<footer>
    <p>eddcase/lamp-stack &mdash; custom unraid docker image</p>
    <p><a href="https://github.com/EddCase/unraid-lamp-stack" target="_blank">github.com/EddCase/unraid-lamp-stack</a></p>
</footer>

<div id="modal-overlay">
    <div id="modal-box">
        <h3>⚠ Delete Site</h3>
        <p>Are you sure you want to permanently delete <strong id="modal-site-name"></strong>?<br>
           This removes the site folder, vhost config, and Pi-hole DNS record.<br>
           <em style="color:var(--red)">This cannot be undone.</em></p>
        <div class="modal-actions">
            <button class="btn-ghost" onclick="closeModal()">Cancel</button>
            <button class="btn btn-danger" onclick="executeDelete()">Yes, Delete</button>
        </div>
    </div>
</div>

<div id="toast">
    <button class="toast-close" onclick="hideToast()">✕</button>
    <div class="toast-title" id="toast-title"></div>
    <div id="toast-body"></div>
</div>

<script>
    let pendingDeleteSite = null;

    function createSite() {
        const input    = document.getElementById('new-site-name');
        const siteName = input.value.trim();
        if (!siteName) { showToast('error', 'Missing Input', 'Please enter a site name.'); input.focus(); return; }
        if (!/^[a-zA-Z0-9_\-]+$/.test(siteName)) {
            showToast('error', 'Invalid Name', 'Letters, numbers, hyphens and underscores only.');
            input.focus(); return;
        }
        const btn = document.getElementById('btn-create');
        btn.disabled = true;
        btn.innerHTML = '<span class="spinner"></span>Creating…';
        postAction({ action: 'create', site: siteName }, function(data) {
            btn.disabled = false;
            btn.innerHTML = '+ Create Site';
            if (data.success) {
                showToast('success', 'Site Created', data.message);
                input.value = '';
                addCard(siteName);
            } else {
                showToast('error', 'Failed', data.message);
            }
        });
    }

    function confirmDelete(site) {
        pendingDeleteSite = site;
        document.getElementById('modal-site-name').textContent = site + '.local';
        document.getElementById('modal-overlay').classList.add('open');
    }

    function closeModal() {
        document.getElementById('modal-overlay').classList.remove('open');
        pendingDeleteSite = null;
    }

    function executeDelete() {
        if (!pendingDeleteSite) return;
        const site = pendingDeleteSite;
        closeModal();
        const btn = document.querySelector(`#card-${CSS.escape(site)} .btn-danger`);
        if (btn) { btn.disabled = true; btn.innerHTML = '<span class="spinner" style="border-top-color:var(--red)"></span>'; }
        postAction({ action: 'delete', site: site }, function(data) {
            if (data.success) {
                showToast('success', 'Site Deleted', data.message, true);
                const card = document.getElementById('card-' + site);
                if (card) {
                    card.style.transition = 'opacity 0.3s';
                    card.style.opacity = '0';
                    setTimeout(() => card.remove(), 320);
                }
                updateCount(-1);
            } else {
                showToast('error', 'Failed', data.message);
                if (btn) { btn.disabled = false; btn.innerHTML = 'Delete'; }
            }
        });
    }

    function postAction(data, callback) {
        const body = Object.entries(data)
            .map(([k, v]) => encodeURIComponent(k) + '=' + encodeURIComponent(v))
            .join('&');
        fetch(window.location.href, {
            method: 'POST',
            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
            body: body
        })
        .then(r => r.json())
        .then(callback)
        .catch(err => showToast('error', 'Network Error', String(err)));
    }

    function addCard(siteName) {
        const grid = document.getElementById('sites-grid');
        const div  = document.createElement('div');
        div.className = 'site-card';
        div.id = 'card-' + siteName;
        div.style.opacity = '0';
        div.style.transition = 'opacity 0.3s';
        div.innerHTML = `
            <div class="site-info">
                <div class="site-icon">🌐</div>
                <div>
                    <a class="site-label site-link" href="http://${esc(siteName)}.local" target="_blank">${esc(siteName)}</a>
                    <div class="site-domain">${esc(siteName)}.local</div>
                </div>
            </div>
            <button class="btn btn-danger" onclick="confirmDelete('${esc(siteName)}')">Delete</button>
        `;
        grid.appendChild(div);
        requestAnimationFrame(() => div.style.opacity = '1');
        updateCount(+1);
    }

    function updateCount(delta) {
        const badge = document.getElementById('site-count-badge');
        if (!badge) return;
        let n = parseInt(badge.textContent) || 0;
        n += delta;
        badge.textContent = n + ' total';
    }

    function showToast(type, title, body, showPihole = false) {
        const toast = document.getElementById('toast');
        document.getElementById('toast-title').textContent = title;
        let html = body
            .replace(/\n/g, '<br>')
            .replace(/&lt;code&gt;(.*?)&lt;\/code&gt;/g, '<code>$1</code>');
        if (showPihole) {
            html += '<br><br><a href="http://192.168.0.6/admin/settings/dnsrecords" target="_blank" '
                  + 'style="display:inline-block;padding:0.3rem 0.75rem;background:rgba(255,165,2,0.12);'
                  + 'color:#ffa502;border:1px solid rgba(255,165,2,0.3);border-radius:6px;'
                  + 'text-decoration:none;font-size:0.78rem;font-weight:600;">'
                  + '&#8599; Remove DNS record in Pi-hole</a>';
        }
        document.getElementById('toast-body').innerHTML = html;
        toast.className = type;
        toast.style.display = 'block';
        clearTimeout(toast._timer);
        toast._timer = setTimeout(hideToast, 9000);
    }

    function hideToast() { document.getElementById('toast').style.display = 'none'; }

    function esc(s) {
        return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
    }

    document.getElementById('modal-overlay').addEventListener('click', e => { if (e.target === e.currentTarget) closeModal(); });
    document.getElementById('new-site-name').addEventListener('keydown', e => { if (e.key === 'Enter') createSite(); });
    document.addEventListener('keydown', e => { if (e.key === 'Escape') closeModal(); });
</script>
</body>
</html>
